"""empty message

Revision ID: 215dcc9d8470
Revises: 67184a015a20
Create Date: 2022-06-03 16:16:18.105625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '215dcc9d8470'
down_revision = '67184a015a20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('associations', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('associations', 'issues_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('associations', 'issues_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('associations', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
