"""empty message

Revision ID: 3489401f20e7
Revises: 60b93c930217
Create Date: 2022-07-05 21:41:29.579872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3489401f20e7'
down_revision = '60b93c930217'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('message', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    # ### end Alembic commands ###
