"""empty message

Revision ID: 606d09c9796b
Revises: d7f509456966
Create Date: 2022-06-02 16:53:41.353116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '606d09c9796b'
down_revision = 'd7f509456966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('issues', sa.Column('question', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'issues', ['name'])
    op.drop_column('issues', 'issue3')
    op.drop_column('issues', 'issue1')
    op.drop_column('issues', 'issue2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('issue2', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('issues', sa.Column('issue1', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('issues', sa.Column('issue3', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'issues', type_='unique')
    op.drop_column('issues', 'question')
    op.drop_column('issues', 'name')
    # ### end Alembic commands ###
