"""empty message

Revision ID: 67184a015a20
Revises: 
Create Date: 2022-06-03 16:10:01.059249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67184a015a20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue1', sa.Integer(), nullable=False),
    sa.Column('issue2', sa.Integer(), nullable=True),
    sa.Column('issue3', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('condition1', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('associations',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('issues_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['issues_id'], ['issues.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('associations')
    op.drop_table('user')
    op.drop_table('issues')
    op.drop_table('answer')
    # ### end Alembic commands ###
