"""empty message

Revision ID: 9151fe8491d1
Revises: ca7ed93cd1ab
Create Date: 2022-06-02 15:28:54.503061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9151fe8491d1'
down_revision = 'ca7ed93cd1ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('condition1', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'condition1')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
