"""empty message

Revision ID: a960a653ab32
Revises: 5daeedc47dbe
Create Date: 2022-06-09 17:03:34.775718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a960a653ab32'
down_revision = '5daeedc47dbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('time', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
