"""empty message

Revision ID: dfaa7fe4a640
Revises: 3ba833a24c4d
Create Date: 2022-06-13 19:56:37.867440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfaa7fe4a640'
down_revision = '3ba833a24c4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answer', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answer', 'user_id',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
