"""empty message

Revision ID: fc9bc8755a66
Revises: 20aecc8d1e64
Create Date: 2022-06-13 17:43:09.995705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc9bc8755a66'
down_revision = '20aecc8d1e64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('answer_user_id_fkey', 'answer', type_='foreignkey')
    op.drop_column('answer', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('answer_user_id_fkey', 'answer', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
