"""empty message

Revision ID: fce9d9cc9105
Revises: 9ab5987441f8
Create Date: 2022-07-06 21:14:09.199744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fce9d9cc9105'
down_revision = '9ab5987441f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('med_info')
    op.drop_table('issues')
    op.drop_table('medications')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('med_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='medications_pkey')
    )
    op.create_table('issues',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='issues_pkey'),
    sa.UniqueConstraint('name', name='issues_name_key')
    )
    op.create_table('med_info',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('dosage', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='med_info_pkey'),
    sa.UniqueConstraint('date', name='med_info_date_key'),
    sa.UniqueConstraint('dosage', name='med_info_dosage_key')
    )
    # ### end Alembic commands ###
